on:
  pull_request_target:
    branches: 
      - main
    types:
      - closed

jobs:
  deploy:
    if: ${{github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: npm run deploy
